spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 123456789123456789123456789123456789

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---

spring:
  profiles: window
  datasource:
    url: jdbc:h2:file:C:/Users