INSERT INTO RESTAURANT(ADDRESS,NAME) VALUES("서울시 강남구 강남대로94길 21","성전 떡볶이");
INSERT INTO RESTAURANT(ADDRESS,NAME) VALUES("서울시 강남구 강남대로94길 9","마법사 주방");
INSERT INTO RESTAURANT(ADDRESS,NAME) VALUES("부산 해운대구 좌동순환로 28","밀면 넘어져요");